# Generated by Django 3.1.3 on 2020-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.TextField(max_length=20)),
                ('e_name', models.TextField(max_length=100)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_contact', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'Empregado',
            },
        ),
    ]
